version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: trellin-backend
    restart: unless-stopped
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    networks:
      - trellin-network
    volumes:
      - ./backend/src:/app/src:cached
      - ./backend/package.json:/app/package.json:ro
      - ./backend/pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: trellin-frontend
    restart: unless-stopped
    ports:
      - "0.0.0.0:5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://4.240.103.28:3001/api/v1
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - trellin-network
    volumes:
      - ./frontend/src:/app/src:cached
      - ./frontend/public:/app/public:cached
      - ./frontend/index.html:/app/index.html:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - ./frontend/vite.config.ts:/app/vite.config.ts:ro
      - ./frontend/tsconfig.json:/app/tsconfig.json:ro
      - ./frontend/tsconfig.app.json:/app/tsconfig.app.json:ro
      - frontend_node_modules:/app/node_modules

networks:
  trellin-network:
    driver: bridge

volumes:
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local
